name: "HCL AppScan DAST"
on:
  push
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ASoC DAST Scan
        uses: antonychiu2/asoc-dast-action@v0.0.3.3
        with:
          baseurl:  https://cloud.appscan.com
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: acd3ef50-6276-461d-8514-abc6e7113577
          scan_type: 'staging'
          dynamic_scan_type: dast
          starting_URL: 'https://demo.testfire.net?mode=demo'
          login_user: jsmith
          login_pass: demo1234
          network: public
          fail_for_noncompliance: false
          wait_for_analysis: true
          wait_for_analysis_timeout_minutes: 60
