name: "Test Workflow"
on:
  #push
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run test nodejs workflow
        uses: antonychiu2/custom-action-workspace@main
  